// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiqVpXCj7MTX6izuHpuTXD0PMu0YAhU0k',
    appId: '1:467245134639:web:f4b8eb4b574b916b22a7da',
    messagingSenderId: '467245134639',
    projectId: 'gaurav-arion-001-e533e',
    authDomain: 'gaurav-arion-001-e533e.firebaseapp.com',
    //storageBucket: 'gaurav-arion-001-e533e.firebasestorage.app',
    storageBucket: 'gaurav-arion-001-e533e.appspot.com',
    measurementId: 'G-9978J44FZS',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpviyS7NfWWWad7QgmHCyu1zRzefszSs8',
    appId: '1:467245134639:ios:d21ebb7fdc28694022a7da',
    messagingSenderId: '467245134639',
    projectId: 'gaurav-arion-001-e533e',
    storageBucket: 'gaurav-arion-001-e533e.firebasestorage.app',
    iosBundleId: 'com.example.kpiAdmin',
  );
}
