// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyBOADpH-ncKO9Zlpr5PknM2cvE9x4vA8xc",
  authDomain: "gaurav-arion-001-3d94a.firebaseapp.com",
  projectId: "gaurav-arion-001-3d94a",
  storageBucket: "gaurav-arion-001-3d94a.firebasestorage.app",
  messagingSenderId: "835979174130",
  appId: "1:835979174130:web:53e028fa890ddc33dff06b"
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCpviyS7NfWWWad7QgmHCyu1zRzefszSs8',
    appId: '1:467245134639:ios:d21ebb7fdc28694022a7da',
    messagingSenderId: '467245134639',
    projectId: 'gaurav-arion-001-3d94a',
    storageBucket: 'gaurav-arion-001-3d94a.firebasestorage.app',
    iosBundleId: 'com.example.kpiAdmin',
  );

}